server.port=8819
spring.application.name=payment-service
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==========================================
# VNPAY CONFIG
# Lấy từ: https://sandbox.vnpayment.vn/merchantv2/
# ==========================================
vnpay.tmn-code=LQ1203S3
vnpay.hash-secret=W6TN4MW8V926K3YV6L3WP6UETFMF03F3
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# URL backend nhận callback từ VNPay (phải public, dùng ngrok khi dev local)
vnpay.return-url=http://localhost:8819/api/payments/vnpay/return
# URL FE redirect sau khi thanh toán xong
vnpay.frontend-success-url=http://localhost:3000/my-orders
vnpay.frontend-fail-url=http://localhost:3000/checkout