server.port=8819
spring.application.name=payment-service
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# VNPAY
vnpay.tmn-code=LQ1203S3
vnpay.hash-secret=30F753TNRCBSBBHZ8XUWT05V3UP84VSN
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://nvt2123.ngrok.io/api/payments/vnpay/return
vnpay.frontend-success-url=http://localhost:3000/my-orders
vnpay.frontend-fail-url=http://localhost:3000/checkout